# Assignment - 3:
# Task - 1:

Question - 1:

Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [1]:
# defining the function for division operation
# which will perform input from the user:
def test():
    a = int(input('Enter numerator number:'))
    b = int(input('Enter denominator number:'))
    print('Result of DIvision: '+str(a/b))
    
# try block:
try:
    test() # calling the test function
# except block handling code for division by zero:
except ZeroDivisionError:
    print('You have divided a number by zero, which is not allowed.')
# except block handling code for wrong value type:
except ValueError:
    print('You must enter integer value')

Enter numerator number:5
Enter denominator number:0
You have divided a number by zero, which is not allowed.


Question - 2:

Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

In [16]:
# generating a list for subjects:
subjects=['Americans','Indians']
# generating a list for verbs:
verbs=['Play', 'watch']
# generating a list for objects:
objects=['Baseball','cricket']

# use loops over each of the predicates like nested for loops for achieving the results:
for i in range(len(subjects)):
    for j in range(len(verbs)):
        for k in range(len(objects)):
            # printing the list in a required output
            print("{} {} {}.".format(subjects[i], verbs[j], objects[k]))

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


# Task - 2:

Question - 1:

Write a function so that the columns of the output matrix are powers of the input vector.  

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 
 
 

In [9]:
import numpy as np
x = np.array([1,2,3,5])
N = 3
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [11]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [12]:
x = np.array([1,2,3,5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [13]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [14]:
np.linalg.det(np.vander(x))

48.00000000000003

In [15]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48